### ISSUE TITLE
药监局那个站可以用这个吗?

### ISSUE THREAD

**Issue by MusaZhou** [sml2h3/mmewmd_crack_for_wenshu#3]
http://qy1.sfda.gov.cn/datasearchcnda/face3/base.jsp?tableId=25&tableName=TABLE25&title=%E5%9B%BD%E4%BA%A7%E8%8D%AF%E5%93%81&bcId=152904713761213296322795806604

**Comment by sml2h3** [comment]
理论上可以，实际操作应该需要再进一步，感觉是另一个版本，有时间研究一下
